[2025-01-25T09:30:42.922+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.filter_data scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T09:30:42.932+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.filter_data scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T09:30:42.933+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T09:30:42.949+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): filter_data> on 2025-01-24 00:00:00+00:00
[2025-01-25T09:30:42.954+0000] {standard_task_runner.py:57} INFO - Started process 91 to run task
[2025-01-25T09:30:42.957+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'filter_data', 'scheduled__2025-01-24T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmp6u3_ttbg']
[2025-01-25T09:30:42.959+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask filter_data
[2025-01-25T09:30:43.021+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.filter_data scheduled__2025-01-24T00:00:00+00:00 [running]> on host bc5f62e6ab49
[2025-01-25T09:30:43.298+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='filter_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-24T00:00:00+00:00'
[2025-01-25T09:30:43.303+0000] {logging_mixin.py:149} INFO - Last processed date: 0001-01-01 00:00:00
[2025-01-25T09:30:43.304+0000] {etl.py:30} INFO - Filtering data after 0001-01-01 00:00:00
[2025-01-25T09:30:43.305+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airqino_etl_to_mongo.py", line 20, in filter_data
    return filter_new_data(data, last_processed_date)
  File "/opt/airflow/dags/utils/etl.py", line 31, in filter_new_data
    filtered_df = df[df['timestamp'] > last_processed_date]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arraylike.py", line 48, in __gt__
    return self._cmp_method(other, operator.gt)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 5502, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 284, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
[2025-01-25T09:30:43.320+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=airqino_etl_to_mongo, task_id=filter_data, execution_date=20250124T000000, start_date=20250125T093042, end_date=20250125T093043
[2025-01-25T09:30:43.333+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task filter_data ('>' not supported between instances of 'str' and 'datetime.datetime'; 91)
[2025-01-25T09:30:43.347+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-01-25T09:30:43.377+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
