[2025-01-25T10:22:29.226+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:22:29.236+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:22:29.236+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T10:22:29.254+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T10:22:29.259+0000] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2025-01-25T10:22:29.262+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmp99eyngnb']
[2025-01-25T10:22:29.264+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask last_processed_date
[2025-01-25T10:22:29.331+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host bc5f62e6ab49
[2025-01-25T10:22:29.436+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T10:22:29.443+0000] {python.py:183} INFO - Done. Returned value was: 0001-01-01 00:00:00
[2025-01-25T10:22:29.474+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T102229, end_date=20250125T102229
[2025-01-25T10:22:29.522+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-01-25T10:22:29.552+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T10:28:39.083+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:28:39.093+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:28:39.093+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T10:28:39.111+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T10:28:39.115+0000] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2025-01-25T10:28:39.119+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmpvhwxb73b']
[2025-01-25T10:28:39.120+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask last_processed_date
[2025-01-25T10:28:39.188+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host bc5f62e6ab49
[2025-01-25T10:28:39.301+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T10:28:39.306+0000] {python.py:183} INFO - Done. Returned value was: 1677-09-21 00:12:43.145224193
[2025-01-25T10:28:39.317+0000] {xcom.py:640} ERROR - Object of type Timestamp is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-01-25T10:28:39.319+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 171, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas._libs.tslibs.timestamps.Timestamp'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2384, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 243, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable
[2025-01-25T10:28:39.335+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T102839, end_date=20250125T102839
[2025-01-25T10:28:39.348+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 23 for task last_processed_date (Object of type Timestamp is not JSON serializable; 74)
[2025-01-25T10:28:39.380+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-01-25T10:28:39.411+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T10:36:59.082+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:36:59.091+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:36:59.092+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T10:36:59.108+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T10:36:59.114+0000] {standard_task_runner.py:57} INFO - Started process 386 to run task
[2025-01-25T10:36:59.118+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmp1yjadcsn']
[2025-01-25T10:36:59.119+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask last_processed_date
[2025-01-25T10:36:59.210+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host bc5f62e6ab49
[2025-01-25T10:36:59.323+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T10:36:59.327+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 2192, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 357, in pandas._libs.tslibs.conversion.datetime_to_datetime64
  File "pandas/_libs/tslibs/np_datetime.pyx", line 120, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1-01-01 00:00:00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airqino_etl_to_mongo.py", line 20, in last_processed_date
    last_processed= pd.to_datetime(last_processed)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 914, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 408, in _convert_listlike_datetimes
    allow_object=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 2198, in objects_to_datetime64ns
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 2187, in objects_to_datetime64ns
    allow_mixed=allow_mixed,
  File "pandas/_libs/tslib.pyx", line 379, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 606, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 602, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 474, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslibs/np_datetime.pyx", line 120, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1-01-01 00:00:00
[2025-01-25T10:36:59.346+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T103659, end_date=20250125T103659
[2025-01-25T10:36:59.387+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 25 for task last_processed_date (Out of bounds nanosecond timestamp: 1-01-01 00:00:00; 386)
[2025-01-25T10:36:59.418+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-01-25T10:36:59.448+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T10:42:06.220+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:42:06.231+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:42:06.232+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T10:42:06.253+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T10:42:06.259+0000] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2025-01-25T10:42:06.264+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmp9kwxn4jz']
[2025-01-25T10:42:06.265+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask last_processed_date
[2025-01-25T10:42:06.336+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host bc5f62e6ab49
[2025-01-25T10:42:06.445+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T10:42:06.449+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airqino_etl_to_mongo.py", line 20, in last_processed_date
    last_processed= pd.to_datetime(last_processed[:10])
TypeError: 'datetime.datetime' object is not subscriptable
[2025-01-25T10:42:06.464+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T104206, end_date=20250125T104206
[2025-01-25T10:42:06.476+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 28 for task last_processed_date ('datetime.datetime' object is not subscriptable; 74)
[2025-01-25T10:42:06.524+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-01-25T10:42:06.555+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T10:43:49.240+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:43:49.250+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:43:49.250+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T10:43:49.266+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T10:43:49.270+0000] {standard_task_runner.py:57} INFO - Started process 173 to run task
[2025-01-25T10:43:49.273+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmpt3vfad2r']
[2025-01-25T10:43:49.275+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask last_processed_date
[2025-01-25T10:43:49.343+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host bc5f62e6ab49
[2025-01-25T10:43:49.455+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T10:43:49.458+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 2192, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 357, in pandas._libs.tslibs.conversion.datetime_to_datetime64
  File "pandas/_libs/tslibs/np_datetime.pyx", line 120, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1-01-01 00:00:00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airqino_etl_to_mongo.py", line 20, in last_processed_date
    last_processed= pd.to_datetime(last_processed)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 914, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 408, in _convert_listlike_datetimes
    allow_object=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 2198, in objects_to_datetime64ns
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 2187, in objects_to_datetime64ns
    allow_mixed=allow_mixed,
  File "pandas/_libs/tslib.pyx", line 379, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 606, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 602, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 474, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslibs/np_datetime.pyx", line 120, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1-01-01 00:00:00
[2025-01-25T10:43:49.474+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T104349, end_date=20250125T104349
[2025-01-25T10:43:49.486+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 30 for task last_processed_date (Out of bounds nanosecond timestamp: 1-01-01 00:00:00; 173)
[2025-01-25T10:43:49.496+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-01-25T10:43:49.526+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T10:49:01.802+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:49:01.812+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:49:01.813+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T10:49:01.828+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T10:49:01.835+0000] {standard_task_runner.py:57} INFO - Started process 407 to run task
[2025-01-25T10:49:01.839+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmpyr3nigw7']
[2025-01-25T10:49:01.840+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask last_processed_date
[2025-01-25T10:49:01.902+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host bc5f62e6ab49
[2025-01-25T10:49:02.004+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T10:49:02.014+0000] {python.py:183} INFO - Done. Returned value was: 0001-01-01 00:00:00
[2025-01-25T10:49:02.047+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T104901, end_date=20250125T104902
[2025-01-25T10:49:02.103+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-01-25T10:49:02.135+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T10:51:12.644+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:51:12.654+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T10:51:12.654+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T10:51:12.674+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T10:51:12.680+0000] {standard_task_runner.py:57} INFO - Started process 529 to run task
[2025-01-25T10:51:12.685+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmprxvg90z9']
[2025-01-25T10:51:12.686+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask last_processed_date
[2025-01-25T10:51:12.750+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host bc5f62e6ab49
[2025-01-25T10:51:12.853+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T10:51:12.854+0000] {python.py:183} INFO - Done. Returned value was: 2020-01-01
[2025-01-25T10:51:12.887+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T105112, end_date=20250125T105112
[2025-01-25T10:51:12.904+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-01-25T10:51:12.934+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T11:31:28.488+0000] {taskinstance.py:1119} INFO - Dependencies not met for <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-01-25T11:31:28.490+0000] {local_task_job_runner.py:161} INFO - Task is not able to be run
[2025-01-25T11:33:04.218+0000] {taskinstance.py:1119} INFO - Dependencies not met for <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-01-25T11:33:04.229+0000] {local_task_job_runner.py:161} INFO - Task is not able to be run
[2025-01-25T11:34:29.132+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T11:34:29.142+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T11:34:29.142+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T11:34:29.158+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T11:34:29.162+0000] {standard_task_runner.py:57} INFO - Started process 426 to run task
[2025-01-25T11:34:29.165+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmp9qj0a0bc']
[2025-01-25T11:34:29.167+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask last_processed_date
[2025-01-25T11:34:29.230+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host b6cb9c2ddee3
[2025-01-25T11:34:29.335+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T11:34:29.336+0000] {python.py:183} INFO - Done. Returned value was: 2020-01-01
[2025-01-25T11:34:29.367+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T113429, end_date=20250125T113429
[2025-01-25T11:34:29.386+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-01-25T11:34:29.416+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T11:36:25.329+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T11:36:25.338+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T11:36:25.339+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T11:36:25.357+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T11:36:25.362+0000] {standard_task_runner.py:57} INFO - Started process 552 to run task
[2025-01-25T11:36:25.366+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmpmsxwdaic']
[2025-01-25T11:36:25.367+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask last_processed_date
[2025-01-25T11:36:25.430+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host b6cb9c2ddee3
[2025-01-25T11:36:25.532+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T11:36:25.534+0000] {python.py:183} INFO - Done. Returned value was: 2020-01-01
[2025-01-25T11:36:25.565+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T113625, end_date=20250125T113625
[2025-01-25T11:36:25.585+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-01-25T11:36:25.615+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T11:37:47.894+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T11:37:47.904+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T11:37:47.904+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T11:37:47.920+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T11:37:47.924+0000] {standard_task_runner.py:57} INFO - Started process 671 to run task
[2025-01-25T11:37:47.928+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmpuvzhpeee']
[2025-01-25T11:37:47.930+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask last_processed_date
[2025-01-25T11:37:47.990+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host b6cb9c2ddee3
[2025-01-25T11:37:48.091+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T11:37:48.093+0000] {python.py:183} INFO - Done. Returned value was: 2020-01-01
[2025-01-25T11:37:48.124+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T113747, end_date=20250125T113748
[2025-01-25T11:37:48.148+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-01-25T11:37:48.178+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T11:38:39.910+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T11:38:39.919+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T11:38:39.920+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-25T11:38:39.934+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): last_processed_date> on 2025-01-24 00:00:00+00:00
[2025-01-25T11:38:39.938+0000] {standard_task_runner.py:57} INFO - Started process 772 to run task
[2025-01-25T11:38:39.941+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airqino_etl_to_mongo', 'last_processed_date', 'manual__2025-01-24T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/airqino_etl_to_mongo.py', '--cfg-path', '/tmp/tmp40ydygnm']
[2025-01-25T11:38:39.943+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask last_processed_date
[2025-01-25T11:38:40.007+0000] {task_command.py:410} INFO - Running <TaskInstance: airqino_etl_to_mongo.last_processed_date manual__2025-01-24T00:00:00+00:00 [running]> on host b6cb9c2ddee3
[2025-01-25T11:38:40.111+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airqino_etl_to_mongo' AIRFLOW_CTX_TASK_ID='last_processed_date' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T00:00:00+00:00'
[2025-01-25T11:38:40.113+0000] {python.py:183} INFO - Done. Returned value was: 2025-01-25 00:00:00
[2025-01-25T11:38:40.145+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=airqino_etl_to_mongo, task_id=last_processed_date, execution_date=20250124T000000, start_date=20250125T113839, end_date=20250125T113840
[2025-01-25T11:38:40.161+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-01-25T11:38:40.194+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
